CREATE TABLE [dbo].[FactCustOrder]
(
	[orderId] INT NOT NULL,
	[lineId] INT NOT NULL,
	[historyId] INT NOT NULL,
	[orderDateKey] INT NOT NULL,
	[statusDateKey] INT NOT NULL,
	[bookSk] INT NOT NULL,
	[customerSk] INT NOT NULL,
	[destDeliverySiteSk] INT NOT NULL,
	[shippingMethodSk] INT NOT NULL,
	[publisherSk] INT NOT NULL,
	[price] DECIMAL(5, 2) NOT NULL,
	[quantity] INT NOT NULL,
	[orderDate] DATETIME NOT NULL,
	[lastStatusId] INT NOT NULL,
	[lastStatusDate] DATETIME NOT NULL,
	[lastOrderStatus] VARCHAR(20) NOT NULL,
	--CONSTRAINT pk_FactCustOrder PRIMARY KEY([orderId],[lineId],[historyId]),
	CONSTRAINT fk_DimBook FOREIGN KEY([bookSk]) REFERENCES [dbo].[DimBook]([bookSk]),
	CONSTRAINT fk_DimCustomer FOREIGN KEY([customerSk]) REFERENCES [dbo].[DimCustomer]([customerSk]),
	CONSTRAINT fk_DimDeliverySite FOREIGN KEY([destDeliverySiteSk]) REFERENCES [dbo].[DimDeliverySite]([deliverySiteSk]),
	CONSTRAINT fk_DimShippingMethod FOREIGN KEY([shippingMethodSk]) REFERENCES [dbo].[DimShippingMethod]([shippingMethodSk]),
	CONSTRAINT fk_DimPublisher FOREIGN KEY([publisherSk]) REFERENCES [dbo].[DimPublisher]([publisherSk]),
	CONSTRAINT fk_DimDate_orderDate FOREIGN KEY([orderDateKey]) REFERENCES [dbo].[DimDate] ([dateKey]),
	CONSTRAINT fk_DimDate_statusDate FOREIGN KEY([statusDateKey]) REFERENCES [dbo].[DimDate] ([dateKey]),
	INDEX ix_order NONCLUSTERED ([orderId]),
	INDEX ix_order_status NONCLUSTERED ([orderId],[lineId])
)
GO
